### ISSUE TITLE
ACL: design and brain storming

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/dbreboot#27]
We need to agree on many things, hence I created this issue. Below is a list of few points that we need to agree on:

Here is a list of few points to get started
- Object types 
  - collection (entire set)
  - object (single object)
  - action (method call) ?
- Permission 
  - read  
  - write
  - delete
  - admin (alias for read, write, and delete)
  - (a method call can be visualized as write permission on an action object)
- Role
  - user
  - group ?

## ACL Object
An ACL object should define the following
- object to control 
  - collection
  - collection + object (with object ID)
- set of permissions (a bit map?) of (read, write, and delete)

## Role
- A user  can be associated with with one or more ACL objects
- A group (are we gonna support groups?) can be associated with with one or more ACL objects
- By default the bcdb owner has full access to the ACL collection (no ACL consultancy should be done) , so he can edit other users access.

## Applying the ACL
We also need to discuss how we going to check authorization of a request (knowing the user identity) efficiently and check against the requested object.

**Comment by muhamadazmy** [comment]
Since objects in bcdb are flat, there is no way we can apply `acl policy` on a hierarchy. Buy may be also in case u want to apply a single ACL on a group of objects (rather than assigning to each ACL) that the objects themself get an extra attribute (group?) and the ACL then can has this group ID (like how unix fs groups work on files)

**Comment by zaibon** [comment]
I don't think ACL should apply on method calls.

Regarding groups, we need to support it too. A group is a list of threebot ID and a name.

the rest looks ok to me.

**Comment by muhamadazmy** [comment]
> Regarding groups, we need to support it too. A group is a list of threebot ID and a name.

We probably also need to have a way to group multiple objects so a single ACL can apply to many objects

**Comment by zaibon** [comment]
> We probably also need to have a way to group multiple objects so a single ACL can apply to many objects

I would only apply on a full collection. So a user can define one ACL for a full reservation.
But if he needs to have special ACL on certain object, the ACL of the object takes preference on the collection one.

So when reaching an object, we check:
- is there an ACL for this object
  - yes -> use this ACL
  - no -> check collection

**Comment by muhamadazmy** [comment]
We probably need to define some real life use cases, because I keep thinking that at some point you would like to apply the same ACL to many many objects, with your solution then we will have to recreate the same ACL object many times.

**Comment by zaibon** [comment]
indeed, but I don't really see the problem. ACL doesn't take storage space. 
So just working on object and collection allow to not have to create more API to deal with object group.

What use case do you think of that is not covered by this ?

**Comment by LeeSmet** [comment]
With this flow we'll also have to choose how we'll handle collections, as right now that doesn't happen yet. 

Also, as far as I recall from last weeks meeting, it was said we wanted to specify for each data object which is stored, what it's ACL is no? i.e. the data object has the data and a pointer to the ACL

**Comment by muhamadazmy** [comment]
The data object also now accepts an acl reference. Currently no validation is done on the ref if it actually points to a valid acl object. But this can be easily done.

The grpc service to manage ACL object is also complete
