### ISSUE TITLE
Storage: add support to choose the namespace, and `list`

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/dbreboot#28]
Currently, Storage trait only exposes a `set` and a `get` method and the ZDB implementation does not support choosing the namespace

We need the following
- Support choosing the namespace
- Support namespace SCAN (iterate over all objects)

We need both functionality to implement #21

**Comment by LeeSmet** [comment]
Closed in d45c24855bf2178082c8e74de1e0ec3fad323903
