### ISSUE TITLE
Create storage layer api

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/dbreboot#3]
Define the minimum api we need to have to be able to write and read data (binary blobs) from the storage layer

**Comment by muhamadazmy** [comment]
I think this is also covered by [bcdb.proto](https://github.com/threefoldtech/dbreboot/blob/master/proto/bcdb.proto) 

- The `set` call accepts both meta + binary blob
- The `update` call accepts only ID + Meta to update meta associated with binary blob.

> Remember we discussed supporting large binary blobs (multipart upload) and we kinda agreed it won't be supported at this stage (or ever)

If this is not enough for the use case, please explain what is needed
