### ISSUE TITLE
explorer address must end with a slash

### ISSUE THREAD

**Issue by abom** [threefoldtech/dbreboot#37]
When trying to start `dbreboot`, explorer address must end with a slash

```
/target/release/dbreboot --explorer https://explorer.grid.tf/explorer/ --seed-file ghanem.seed -l 127.0.0.1:50051
```

If it's passed like ` --explorer https://explorer.grid.tf/explorer` (without a trailing slash), `join` method [won't work as expected](https://docs.rs/url/2.1.1/url/struct.Url.html#method.join) and `get_user` request will be sent to `https://explorer.grid.tf/users` instead of `https://explorer.grid.tf/explorer/users`, which will fail with 404:

```
panic: rpc error: code = Unauthenticated desc = could not get user key: failed to get user: invalid type: integer `404`, expected struct User at line 1 column 3
```

**Comment by muhamadazmy** [comment]
Fixed
